### ISSUE TITLE
Add scheduled CI to retrieve github stars for all notebooks that have github links attached to them.

### ISSUE THREAD

**Issue by duerrsimon** [colab-db/colab-db.github.io#2]
Could use: https://pygithub.readthedocs.io/en/latest/examples/Repository.html#get-count-of-stars

**Comment by duerrsimon** [comment]
I wanted to store the different notebooks in seperate folders
```
colab
 - colab-unique-slug.md
 - colab2-unique-slug.md
binder
 - binder-unique-slug.md
huggingface
 - hf-unique-slug.md
```
I think the most sensible thing to do would therefore be to iterate over the different folders and build a json file with similar structure


For Binder and colab notebooks I would check the `md` file, parse the header and read the url of the github repo and use pygithub to extract the number of stars. 
For HF we can use the huggingface api, inspiration here: https://huggingface.co/spaces/Gradio-Blocks/Leaderboard/blob/main/app.py

`stars.json`
```{
"colab": { 
"colab-unique-slug":10,
"colab2-unique-slug": 4
},
"binder": {"binder-unique-slug": 2},
"huggingface":{"hf-unique-slug":2}
}
```
If we wanted to display trendlines for each repo we could eventually change it to `"colab-unique-slug":[0, 2, 4, 10]`

**Comment by duerrsimon** [comment]
I think it would be nice in the same step to generate once a day a `tags.json` and `usedsoftware.json` with 

```
{"tags":{
"tag-1": count
}}
```

With this we can sort the tags/software by frequency and display them for the submission form so that people do not create multiple versions of the same tag with different capitalization etc. 

The format of the `md` file for parsing will something like this:

```
---
title: AlphaFold2 - ColabFold
description: Standard AlphaFold pipeline using MMseqs2
git: sokrypton/ColabFold
url: https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb
license: mit
type: colab
category: biology
tags:
 - Bio
 - structure prediction
image: https://github.com/sokrypton/ColabFold/raw/main/.github/ColabFold_Marv_Logo.png
added: 04.06.2022
used_software:
 - py3Dmol
 - jax
 - alphafold
creator:
 - 
  name: Sergey Ovchinnikov
  twitter: sokrypton
  github: sokrypton
 - 
  name: Milot Mirdita
  twitter: milot_mirdita
  github: milot-mirdita
---

# ColabFold - AlphaFold

Runs AlphaFold using MMseqs2
```
